environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload 'http://slproweb.com/download/Win32OpenSSL-1_0_2h.exe';
  - ps: Start-Process "Win32OpenSSL-1_0_2h.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait
  - env OPENSSL_LIB_DIR=C:/OpenSSL-Win32 OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win32/include cargo build
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
build: false
test_script:
  - cargo clean
  - cargo build
  - cargo test --verbose
