#[allow(non_snake_case)]
#[derive(RustcDecodable, RustcEncodable)]
pub struct BeamChannel {
    pub id: i32,
    pub userId: i32,
    pub token: String,
    pub online: bool,
    pub featured: bool,
    pub partnered: bool,
    pub transcodingProfileId: i32,
    pub suspended: bool,
    pub name: String,
    pub audience: String,
    pub viewersTotal: i32,
    pub viewersCurrent: i32,
    pub numFollowers: i32,
    pub description: String,
    pub typeId: i32,
    pub interactive: bool,
    pub tetrisGameId: Option<i32>,
    pub ftl: i32,
    pub hasVod: bool,
    pub languageId: Option<i32>,
    pub coverId: i32,
    pub thumbnailId: i32,
    pub badgeId: Option<i32>,
    pub hosteeId: Option<i32>,
    pub createdAt: String,
    pub updatedAt: String,
    pub deletedAt: Option<String>,
}
